name: Implemented CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
  deploy: 
    name: Deploy to Server
    runs-on: self-hosted
    
    steps:  
      - name: Auto Deployment
        run: |
          #!/bin/bash
          
          set -e 

          cd /home/github/CI-CD-Basic

          echo "<== Pulling Repo ==>"
          git config --global --add safe.directory .
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          echo "<== Installing Module ==>"
          npm install

          echo "<== Running App ==>"
          npm run dev

          echo "Deployment Complete"
