name: Implemented CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main


jobs:
  deploy: 
    name: Deploy to Server
    runs-on: self-hosted
    defaults:
      run:
        shell: bash  

    steps:  
      - name: Auto Deployment
        run: |
          set -e 

          cd /home/github/CI-CD-Basic

          echo "<== Pulling Repo ==>"
          git config --global --add safe.directory .
          git fetch origin
          git reset --hard origin/main
          git clean -fd

          echo "<== Installing Module ==>"
          npm install

          echo "<== Running App ==>"
          pm2 delete ci-cd-app || true
          pm2 start server.mjs --name ci-cd-app-basic

          echo "Deployment Complete"
